#!/usr/local/bin/python3

import os
from sys import argv

if len(argv) < 2:
    print ("I need a commit message!")
    exit()

def run_c (cmd):
	print(cmd + "\n")
	os.system(cmd)
	print("")

run_c ("git add -A")
run_c ('git commit -m "' + argv[1] +'"')
run_c ('git push')

