#!/usr/bin/python
import os
from sys import argv

print argv
if len(argv) < 2:
    print ("I need a commit message!")
    exit()

def run_c (cmd):
	print(cmd)
	os.system(cmd)
	print("\n")

run_c ("git add -A")
run_c ('git commit -m "' + argv[1] +'"')
run_c ('git push')

